# Generated by Django 4.1.4 on 2023-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choicemodel",
            name="is_true",
            field=models.BooleanField(default=False),
        ),
    ]
